name: "Zero Trust Handshake"
description: "Implements automation of authentication of workflow call (needs write access to repo)"
inputs:
  mode:
    description: "create/check/cleanup"
    default: "create"
  destination:
    description: "destination is verification info, use with create mode"
    default: ""
  token:
    description: "token created on create stage, use with check and cleanup mode"
    default: ""
  receiver:
    description: "receiver is verification info, use with check mode"
    default: "unknown"
  github_token:
    description: "GitHub Token"
    default: ${{ github.token }}
  expiration_time:
    description: "Handshake expiration time in minutes, use with create mode"
    default: "10"
outputs:
  token:
    description: "token created on create stage"
  check_status:
    description: "true - checked / false - not checked"
runs:
  using: "node20"
  main: "dist/index.js"
