name: Example

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  prepare-for-handshake:
    runs-on: ubuntu-latest

    outputs:
      token: ${{ steps.handshake.outputs.token }}

    steps:
      - name: Prepare for handshake
        id: handshake
        uses: sahlet-official/zero-trust-handshake@latest

  workflow-call:
    name: Call other workflow (it can be workflow in another repo)
    needs: prepare-for-handshake
    if: success()
    uses: sahlet-official/zero-trust-handshake/.github/workflows/handshake-receiver.yml@master
    with:
      caller: "sahlet-official/zero-trust-handshake"
    secrets:
      jwt: ${{ needs.prepare-for-handshake.outputs.token }}