name: Example

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  prepare-for-handshake:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare for handshake
        id: handshake
        uses: sahlet-official/zero-trust-handshake@latest

      - name: 
        uses: sahlet-official/zero-trust-handshake/.github/workflows/handshake-receiver.yml@main
        with:
          jwt: ${{ steps.handshake.outputs.jwt }}
          caller: "sahlet-official/zero-trust-handshake"

  workflow-call:
    name: Call other workflow (it can be workflow in another repo)
    needs: prepare-for-handshake
    if: success()
    uses: sahlet-official/zero-trust-handshake/.github/workflows/handshake-receiver.yml@main
    with:
      jwt: ${{ needs.prepare-for-handshake.outputs.jwt }}
      caller: "sahlet-official/zero-trust-handshake"