name: Example

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  example-step-1:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare for handshake
        id: handshake
        uses: sahlet-official/zero-trust-handshake@latest

      - name: Call other workflow (it can be workflow in another repo)
        uses: sahlet-official/zero-trust-handshake/.github/workflows/handshake-receiver.yml@main
        with:
          jwt: ${{ steps.handshake.outputs.jwt }}
          caller: "sahlet-official/zero-trust-handshake"