name: Example

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  prepare-for-handshake:
    runs-on: ubuntu-latest

    outputs:
      token: ${{ steps.handshake.outputs.token }}

    steps:
      - name: Prepare for handshake
        id: handshake
        uses: sahlet-official/zero-trust-handshake@latest
        with:
          destination: "sahlet-official/zero-trust-handshake/.github/workflows/handshake-receiver.yml@master"

  workflow-call:
    name: Call other workflow (it can be workflow in another repo)
    needs: prepare-for-handshake
    if: ${{ success() }}
    uses: sahlet-official/zero-trust-handshake/.github/workflows/handshake-receiver.yml@master
    with:
      sender: "sahlet-official/zero-trust-handshake"
    secrets:
      token: ${{ needs.prepare-for-handshake.outputs.token }}

  handshake-cleanup:
    runs-on: ubuntu-latest
    needs:
      - prepare-for-handshake
      - workflow-call
    if: ${{ always() && needs.prepare-for-handshake.result == 'success' }}

    steps:
      - name: Handshake cleanup
        uses: sahlet-official/zero-trust-handshake@latest
        with:
          mode: cleanup
          token: ${{ needs.prepare-for-handshake.outputs.token }}