name: Handshake receiver

on:
  workflow_call:
    inputs:
      jwt:
        required: true
        type: string
      caller:
        required: true
        type: string

jobs:
  handshake-insurance:
    name: Respond to handshake
    if: ${{ inputs.caller }} == "sahlet-official/zero-trust-handshake"
    uses: sahlet-official/zero-trust-handshake/.github/workflows/handshake-insurance.yml@main
    with:
      jwt: ${{ inputs.jwt }}
      handshake_receiver: "Example receiver"

  request-processing:
    runs-on: ubuntu-latest
    needs: handshake-insurance
    if: success()
    steps:
      - name: Log handshake result
        run: |
          echo check_status is ${{ needs.handshake-insurance.outputs.check_status }}
      
      - name: Process request
        if: ${{ needs.handshake-insurance.outputs.check_status }} == "true"
        run: |
          echo ✅ Request processed
