name: Handshake receiver

on:
  workflow_call:
    # inputs:
    secrets:
      token:
        required: true

jobs:
  handshake-verification:
    runs-on: ubuntu-latest

    outputs:
      sender: ${{ steps.extraction.outputs.sender }}
      iam_destination: ${{ steps.verification.outputs.iam_destination }}

    steps:
      - name: Extraction
        id: extraction
        uses: sahlet-official/zero-trust-handshake@latest
        with:
          mode: "extract"
          token: "${{ secrets.token }}"

      - name: Verification that I am destination
        id: verification
        run: |
          if [[ "${{ steps.extraction.outputs.destination }}" == "sahlet-official/zero-trust-handshake/.github/workflows/handshake-receiver.yml@master" ]]; then
            echo "iam_destination=true" >> $GITHUB_OUTPUT
          else
            echo "iam_destination=false" >> $GITHUB_OUTPUT
            exit 1
          fi

  handshake-insurance:
    name: Respond to handshake
    needs: handshake-verification
    if: success() && ${{ needs.handshake-verification.outputs.iam_destination == 'true' }}
    uses: sahlet-official/zero-trust-handshake/.github/workflows/handshake-insurance.yml@master
    with:
      handshake_receiver: "Example receiver"
    secrets:
      token: ${{ secrets.token }}

  request-processing:
    runs-on: ubuntu-latest
    needs: handshake-insurance
    if: success() # always()
    steps:
      - name: Log handshake result
        run: |
          echo check_status is ${{ needs.handshake-insurance.outputs.check_status }}

      - name: Reject request
        if: ${{ needs.handshake-insurance.outputs.check_status != 'true' }}
        run: |
          echo ❌ Request rejected
          exit 1
      
      - name: Process request
        if: ${{ needs.handshake-insurance.outputs.check_status == 'true' }}
        run: |
          echo ✅ Request processed
