name: Handshake receiver

on:
  workflow_call:
    inputs:
      caller:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  handshake-insurance:
    name: Respond to handshake
    if: ${{ inputs.caller == 'sahlet-official/zero-trust-handshake' }}
    uses: sahlet-official/zero-trust-handshake/.github/workflows/handshake-insurance.yml@master
    with:
      handshake_receiver: "Example receiver"
    secrets:
      token: ${{ secrets.token }}

  request-processing:
    runs-on: ubuntu-latest
    needs: handshake-insurance
    if: success() # always()
    steps:
      - name: Log handshake result
        run: |
          echo check_status is ${{ needs.handshake-insurance.outputs.check_status }}

      - name: Reject request
        if: ${{ needs.handshake-insurance.outputs.check_status != 'true' }}
        run: |
          echo ❌ Request rejected
          exit 1
      
      - name: Process request
        if: ${{ needs.handshake-insurance.outputs.check_status == 'true' }}
        run: |
          echo ✅ Request processed
