name: Handshake receiver

on:
  workflow_call:
    inputs:
      caller:
        required: true
        type: string
    secrets:
      jwt:
        required: true

jobs:
  handshake-insurance:
    name: Respond to handshake
    if: ${{ inputs.caller }} == 'sahlet-official/zero-trust-handshake1'
    uses: sahlet-official/zero-trust-handshake/.github/workflows/handshake-insurance.yml@master
    with:
      handshake_receiver: "Example receiver"
    secrets:
      jwt: ${{ secrets.jwt }}

  request-processing:
    runs-on: ubuntu-latest
    needs: handshake-insurance
    if: always() # success()
    steps:
      - name: Log handshake result
        run: |
          echo check_status is ${{ needs.handshake-insurance.outputs.check_status }}

      - name: Process request 1
        if: ${{ needs.handshake-insurance.outputs.check_status }} != "true"
        run: |
          echo ❌ Request rejected
      
      - name: Process request 2
        if: ${{ needs.handshake-insurance.outputs.check_status }} == "true"
        run: |
          echo ✅ Request processed
