name: Test

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  test01-wrong-destination:
    runs-on: ubuntu-latest
    if: ${{ always() }}

    outputs:
      token: ${{ steps.handshake.outputs.token }}

    steps:
      - name: Prepare for handshake
        id: handshake
        uses: sahlet-official/zero-trust-handshake@latest
        with:
          sender: "sahlet-official/zero-trust-handshake"
          destination: "wrong-org/wrong-repo/.github/workflows/handshake-receiver.yml@master"

  test01-workflow-call:
    needs: test01-wrong-destination
    if: ${{ always() && needs.test01-wrong-destination.result == 'success' }}
    uses: sahlet-official/zero-trust-handshake/.github/workflows/handshake-receiver.yml@master
    secrets:
      token: ${{ needs.test01-wrong-destination.outputs.token }}

  test01-handshake-cleanup:
    runs-on: ubuntu-latest
    needs:
      - test01-wrong-destination
      - test01-workflow-call
    if: ${{ always() && needs.test01-wrong-destination.result == 'success' }}

    steps:
      - name: Handshake cleanup
        uses: sahlet-official/zero-trust-handshake@latest
        with:
          mode: cleanup
          token: ${{ needs.test01-wrong-destination.outputs.token }}

# ----------------------------------------------------------------------------------------------------------------

  test02-cleanup-before-handshake:
    runs-on: ubuntu-latest
    if: ${{ always() }}

    outputs:
      token: ${{ steps.handshake.outputs.token }}

    steps:
      - name: Prepare for handshake
        id: handshake
        uses: sahlet-official/zero-trust-handshake@latest
        with:
          sender: "sahlet-official/zero-trust-handshake"
          destination: "sahlet-official/zero-trust-handshake/.github/workflows/handshake-receiver.yml@master"

  test02-handshake-cleanup:
    runs-on: ubuntu-latest
    needs:
      - test02-cleanup-before-handshake
    if: ${{ always() && needs.test02-cleanup-before-handshake.result == 'success' }}

    steps:
      - name: Handshake cleanup
        uses: sahlet-official/zero-trust-handshake@latest
        with:
          mode: cleanup
          token: ${{ needs.test02-cleanup-before-handshake.outputs.token }}

  test02-workflow-call:
    needs:
      - test02-handshake-cleanup
      - test02-cleanup-before-handshake
    if: ${{ always() && needs.test02-handshake-cleanup.result == 'success' }}
    uses: sahlet-official/zero-trust-handshake/.github/workflows/handshake-receiver.yml@master
    secrets:
      token: ${{ needs.test02-cleanup-before-handshake.outputs.token }}

# ----------------------------------------------------------------------------------------------------------------

  test03-handshake-cleanup-double:
    runs-on: ubuntu-latest
    needs:
      - test01-handshake-cleanup
      - test01-wrong-destination
    if: ${{ always() && needs.test01-handshake-cleanup.result == 'success' }}

    steps:
      - name: Handshake cleanup
        uses: sahlet-official/zero-trust-handshake@latest
        with:
          mode: cleanup
          token: ${{ needs.test01-wrong-destination.outputs.token }}

# ----------------------------------------------------------------------------------------------------------------

  test04-wrong-signature:
    runs-on: ubuntu-latest
    if: ${{ always() }}

    outputs:
      token: ${{ steps.damage.outputs.token }}

    steps:
      - name: Prepare for handshake
        id: handshake
        uses: sahlet-official/zero-trust-handshake@latest
        with:
          sender: "sahlet-official/zero-trust-handshake"
          destination: "sahlet-official/zero-trust-handshake/.github/workflows/handshake-receiver.yml@master"

      - name: Damage of token signature
        id: damage
        run: |
          encoded_token="${{ steps.handshake.outputs.token }}"
          decoded_token=$(echo "$encoded_token" | base64 --decode)
          damaged_token="${decoded_token}damage"
          encoded_damaged_token=$(echo -n "$damaged_token" | base64)
          echo "token<<EOF" >> $GITHUB_OUTPUT
          echo "$encoded_damaged_token" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  test04-workflow-call:
    needs: test04-wrong-signature
    if: ${{ always() && needs.test04-wrong-signature.result == 'success' }}
    uses: sahlet-official/zero-trust-handshake/.github/workflows/handshake-receiver.yml@master
    secrets:
      token: ${{ needs.test04-wrong-signature.outputs.token }}

  test04-handshake-cleanup:
    runs-on: ubuntu-latest
    needs:
      - test04-wrong-signature
      - test04-workflow-call
    if: ${{ always() && needs.test04-wrong-signature.result == 'success' }}

    steps:
      - name: Handshake cleanup
        uses: sahlet-official/zero-trust-handshake@latest
        with:
          mode: cleanup
          token: ${{ needs.test04-wrong-signature.outputs.token }}

# ----------------------------------------------------------------------------------------------------------------