name: Test

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      # - name: Prepare for handshake (expiration fail)
      #   uses: sahlet-official/zero-trust-handshake@latest
      #   with:
      #     expiration_time: 0